/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './layouts/**/*.html',
    './content/**/*.md',
    './content/**/*.html',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "var(--color-on-primary-container)",
        "on-tertiary": "var(--color-on-tertiary)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary": "var(--color-secondary)",
        "error-container": "var(--color-error-container)",
        "surface-container": "var(--color-surface-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-variant": "var(--color-surface-variant)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-secondary": "var(--color-on-secondary)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary": "var(--color-tertiary)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface": "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "outline": "var(--color-outline)",
        "primary": "var(--color-primary)",
        "surface-tint": "var(--color-surface-tint)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-primary": "var(--color-on-primary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-background": "var(--color-on-background)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-error": "var(--color-on-error)",
        "on-error-container": "var(--color-on-error-container)",
        "background": "var(--color-background)",
        "error": "var(--color-error)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "3rem",
        "container-max": "1280px",
        "section-gap": "8rem",
        "stack-sm": "0.5rem",
        "gutter": "2rem",
        "stack-md": "1.5rem"
      },
      fontFamily: {
        "body-md": ["Work Sans"],
        "button": ["Space Grotesk"],
        "headline-lg": ["Epilogue"],
        "headline-xl": ["Epilogue"],
        "body-lg": ["Work Sans"],
        "label-caps": ["Space Grotesk"],
        "headline-md": ["Epilogue"]
      },
      fontSize: {
        "body-md": ["1rem", {"lineHeight": "1.6", "fontWeight": "400"}],
        "button": ["1rem", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "700"}],
        "headline-lg": ["3rem", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-xl": ["4.5rem", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "body-lg": ["1.25rem", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["0.875rem", {"lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-md": ["2rem", {"lineHeight": "1.3", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
