/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./layouts/**/*.html",
    "./content/**/*.md",
    "./content/**/*.html",
    "./themes/adritian-free-hugo-theme/layouts/**/*.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-container": "#573b00",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffdeac",
        "on-primary-fixed-variant": "#604100",
        "inverse-surface": "#313030",
        "inverse-primary": "#fdbb42",
        "secondary": "#5e5e5e",
        "error-container": "#ffdad6",
        "surface-container": "#f0eded",
        "tertiary-fixed-dim": "#c9c6c0",
        "surface-variant": "#e5e2e1",
        "primary-container": "#dfa129",
        "surface-container-high": "#eae7e7",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#41403c",
        "tertiary": "#5f5e59",
        "secondary-container": "#e2e2e2",
        "tertiary-container": "#aeaca6",
        "surface": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-highest": "#e5e2e1",
        "outline": "#827562",
        "primary": "#7e5700",
        "surface-tint": "#7e5700",
        "tertiary-fixed": "#e5e2db",
        "on-tertiary-fixed-variant": "#474742",
        "on-primary-fixed": "#281900",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e2e2e2",
        "outline-variant": "#d5c4af",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed-variant": "#474747",
        "on-primary": "#ffffff",
        "on-secondary-container": "#646464",
        "on-tertiary-fixed": "#1c1c18",
        "on-surface": "#1c1b1b",
        "primary-fixed-dim": "#fdbb42",
        "on-surface-variant": "#504535",
        "inverse-on-surface": "#f3f0ef",
        "on-background": "#1c1b1b",
        "on-secondary-fixed": "#1b1b1b",
        "secondary-fixed-dim": "#c6c6c6",
        "surface-container-low": "#f6f3f2",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#fcf9f8",
        "error": "#ba1a1a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-lg": "3rem",
        "container-max": "1280px",
        "section-gap": "8rem",
        "stack-sm": "0.5rem",
        "gutter": "2rem",
        "stack-md": "1.5rem"
      },
      "fontFamily": {
        "body-md": ["Work Sans"],
        "button": ["Space Grotesk"],
        "headline-lg": ["Epilogue"],
        "headline-xl": ["Epilogue"],
        "body-lg": ["Work Sans"],
        "label-caps": ["Space Grotesk"],
        "headline-md": ["Epilogue"]
      },
      "fontSize": {
        "body-md": ["1rem", {"lineHeight": "1.6", "fontWeight": "400"}],
        "button": ["1rem", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "700"}],
        "headline-lg": ["3rem", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-xl": ["4.5rem", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "body-lg": ["1.25rem", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["0.875rem", {"lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-md": ["2rem", {"lineHeight": "1.3", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/typography'),
  ],
}
